name: Batch - Build and Deploy (Compose HA)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/team3-batch:latest

      - name: Deploy to Server (Docker Compose Rolling Update)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 8822
          script: |
            set -e
            
            echo "Batch Server Update Start"
            
            export DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
            export DOCKER_PASSWORD="${{ secrets.DOCKER_PASSWORD }}"
            cd ~/infra

            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker compose pull team3-batch-1
            
            echo "Batch-1 Restart"
            docker compose --env-file .env up -d --no-deps --force-recreate team3-batch-1
            
            echo "Batch-1 Health Check"
            for retry in {1..30}; do
              if docker exec team3-batch-1 curl -s http://localhost:8080/actuator/health | grep -q "UP"; then
                  echo "Batch-1 UP"
                  break
              fi
            
              echo "Waiting... ($retry/30)"
              sleep 3
            
              if [ $retry -eq 30 ]; then
                echo "Batch-1 Failed"
                exit 1
              fi
            done
            
            echo "Batch-2 Restart"
            docker compose --env-file .env up -d --no-deps --force-recreate team3-batch-2
            
            echo "Batch-2 Health Check"
            for retry in {1..30}; do
              if docker exec team3-batch-2 curl -s http://localhost:8080/actuator/health | grep -q "UP"; then
                  echo "Batch-2 UP"
                  break
              fi
            
              echo "Waiting... ($retry/30)"
              sleep 3
            
              if [ $retry -eq 30 ]; then
                echo "Batch-2 Failed"
                exit 1
              fi
            done
            
            echo "Batch Server Deploy Complete"
            
            sleep 2
            docker logs --tail 20 team3-batch-1